# Generated by Django 5.2.5 on 2025-09-05 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 13, 29, 55, 730301, tzinfo=datetime.timezone.utc)),
        ),
    ]
