# Generated by Django 5.2.5 on 2025-09-05 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 13, 33, 50, 968509, tzinfo=datetime.timezone.utc)),
        ),
    ]
