# Generated by Django 5.2.6 on 2025-09-14 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 13, 41, 12, 721317, tzinfo=datetime.timezone.utc)),
        ),
    ]
