# Generated by Django 5.2.5 on 2025-09-19 18:29

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0008_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 18, 29, 41, 472825, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(14)])),
                ('numero_telefone', models.CharField(max_length=11)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conta.usuario')),
            ],
        ),
    ]
