# Generated by Django 5.2.5 on 2025-09-19 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0009_alter_usuario_data_nascimento_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 18, 35, 9, 613921, tzinfo=datetime.timezone.utc)),
        ),
    ]
