# Generated by Django 5.2.5 on 2025-09-20 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0012_alter_paciente_cpf_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 20, 2, 7, 29, 268339, tzinfo=datetime.timezone.utc)),
        ),
    ]
