# Generated by Django 5.2.5 on 2025-09-20 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0013_alter_paciente_cpf_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 20, 2, 8, 48, 929454, tzinfo=datetime.timezone.utc)),
        ),
    ]
