# Generated by Django 5.2.5 on 2025-09-20 02:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0014_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 9, 20, 2, 19, 39, 394078, tzinfo=datetime.timezone.utc)),
        ),
    ]
