# Generated by Django 5.0.6 on 2025-10-09 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0017_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2025, 10, 9, 18, 26, 28, 604614, tzinfo=datetime.timezone.utc)),
        ),
    ]
