# Generated by Django 5.0.6 on 2025-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0019_paciente_sexo_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
