# Generated by Django 5.2.6 on 2025-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0020_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estatura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='raca',
            field=models.CharField(blank=True, choices=[('B', 'Branca'), ('P', 'Preta'), ('A', 'Amarela')], max_length=1, null=True),
        ),
    ]
