# Generated by Django 5.0.6 on 2025-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0021_paciente_estatura_paciente_peso_paciente_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estatura',
            field=models.IntegerField(default=160),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
