# Generated by Django 5.0.6 on 2025-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0023_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('P', 'Professor Administrador'), ('A', 'Estudante Avaliador')], default='A', max_length=1),
        ),
    ]
