# Generated by Django 5.2.6 on 2025-09-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0016_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=512)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem da pergunta no questionario')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='conta.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('nota_intensidade', models.PositiveSmallIntegerField(blank=True, help_text='Opcional: nota de intensidade (ex: 0-10)', null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.pergunta')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.questionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
