# Generated by Django 5.0.6 on 2025-10-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0017_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('respostas', models.JSONField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
