# Generated by Django 5.0.6 on 2025-10-10 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0020_alter_usuario_data_nascimento'),
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conta.usuario'),
        ),
    ]
