# Generated by Django 5.0.6 on 2025-10-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_questionario_avaliador'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
