# Generated by Django 5.0.6 on 2025-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_questionario_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
