# Generated by Django 5.2.7 on 2025-11-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_alter_questionario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='respostas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
