# Generated by Django 5.2.6 on 2025-11-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0005_alter_questionario_respostas'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
