# Generated by Django 5.2.6 on 2025-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0006_questionario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='respostas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
