# Generated by Django 5.2.6 on 2025-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0008_questionario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
