# Generated by Django 5.2.6 on 2025-11-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0009_remove_questionario_tipo_alter_questionario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
